### ISSUE TITLE
{not work change Lange}plz help me

### ISSUE THREAD

**Issue by lolminerxmrig** [xzajyjs/ThunderSearch#15]
Hi.
plz help me

![image](https://user-images.githubusercontent.com/108659226/230726828-5325f2a3-edc4-41c3-bb6a-14460485bfb9.png)

**Comment by xzajyjs** [comment]
How do you run it?  Is it through `python ThunderSearch.py` or directly run the `exe` from the release?

**Comment by lolminerxmrig** [comment]
exe

**Comment by xzajyjs** [comment]
After running the exe for the first time, a config file will be generated in the current directory, modify the `language` option in the file to `en` and reopen the exe.  If it does not work, clone the source code, modify the config file and use `python ThunderSearch.py` ​​to run.

**Comment by lolminerxmrig** [comment]
yes me try : 
`After running the exe for the first time, a config file will be generated in the current directory, modify the language option in the file to en and reopen the exe. `
not work.
thanks.

**Comment by xzajyjs** [comment]
`If it does not work, clone the source code, modify the config file and use python ThunderSearch.py ​​to run.`
