### ISSUE TITLE
在macos最新版本上面不能使用，提示已损坏师傅能修复一下吗

### ISSUE THREAD

**Issue by JackeyLov5** [xzajyjs/ThunderSearch#16]

**Comment by xzajyjs** [comment]
经测试Ventura和Sonoma都可以正常使用。已损坏是一个macOS常见问题，参考如下步骤：

1、打开终端；
2、输入以下命令，回车；
```bash
sudo xattr -d com.apple.quarantine /Applications/xxxx.app
```
注意：/Applications/xxxx.app 换成你的App路径,且APP名称之间不能有空格，如果有空格，可以先修改名称，执行后再改回去。
3、重启App即可。

**Comment by JackeyLov5** [comment]
谢谢您



忘了这一茬


------------------ 原始邮件 ------------------
发件人: xzajyjs ***@***.***&gt;
发送时间: 2023年7月15日 10:54
收件人: xzajyjs/ThunderSearch ***@***.***&gt;
抄送: JackeyLov5 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [xzajyjs/ThunderSearch] 在macos最新版本上面不能使用，提示已损坏师傅能修复一下吗 (Issue #16)





 
经测试Ventura和Sonoma都可以正常使用。已损坏是一个macOS常见问题，参考如下步骤：
 
1、打开终端；
 2、输入以下命令，回车；
 sudo xattr -d com.apple.quarantine /Applications/xxxx.app
 注意：/Applications/xxxx.app 换成你的App路径,且APP名称之间不能有空格，如果有空格，可以先修改名称，执行后再改回去。
 3、重启App即可。
