### ISSUE TITLE
运行在mac中时 zoomeye 无法工作

### ISSUE THREAD

**Issue by shiqinzhenya** [xzajyjs/ThunderSearch#22]
![WechatIMG199](https://github.com/xzajyjs/ThunderSearch/assets/93901413/8b7934be-9cad-4199-bd65-69a09010d41b)
<img width="746" alt="image" src="https://github.com/xzajyjs/ThunderSearch/assets/93901413/447bf23e-aba0-4b5f-884d-ce4b65a98a07">

**Comment by xzajyjs** [comment]
模式选择web应用
