### ISSUE TITLE
Proposed increase quake、fofa、hunter

### ISSUE THREAD

**Issue by guchangan1** [xzajyjs/ThunderSearch#3]
It will attract more audiences and get more stars

**Comment by xzajyjs** [comment]
It has already been added to the TODO LIST.

**Comment by guchangan1** [comment]
OK, if so, I will continue to pay attention to your project and look forward to it

**Comment by qigege-ui** [comment]
傻蛋呢

**Comment by apt-kristaps** [comment]
建议增加一种语法联动多种引擎

**Comment by xzajyjs** [comment]
Support Shodan ([v2.4](https://github.com/xzajyjs/ThunderSearch/releases/tag/v2.4))

**Comment by xzajyjs** [comment]
Support Hunter ([v2.5](https://github.com/xzajyjs/ThunderSearch/releases/tag/v2.5))
