### ISSUE TITLE
window如何运行, 我下载了release解压后不知改如何运行

### ISSUE THREAD

**Issue by FairyWorld** [xzajyjs/ThunderSearch#4]
window如何运行, 我下载了release解压后不知改如何运行

**Comment by FairyWorld** [comment]
> window如何运行, 我下载了release解压后不知改如何运行

使用源码可以运行

**Comment by xzajyjs** [comment]
从1.3版本开始不再打包windows版本，有需要请自行打包。计划于2.3重启对windows的打包支持

**Comment by xzajyjs** [comment]
2.3版本已更新
