### ISSUE TITLE
请求作者大大增加Windows支持

### ISSUE THREAD

**Issue by HacKerQWQ** [xzajyjs/ThunderSearch#5]
请求作者大大增加Windows支持

**Comment by xzajyjs** [comment]
v2.3已打包windows版本

**Comment by TajangSec** [comment]
> v2.3已打包windows版本
已保存配置
![image](https://user-images.githubusercontent.com/63721558/188278337-63f490a6-09df-40b7-80ef-4078893f01d1.png)
搜索引擎也选择fofa了，可为什么报错
![image](https://user-images.githubusercontent.com/63721558/188278358-f1be22cc-58f6-47e6-a108-5b1f76c965a0.png)

**Comment by xzajyjs** [comment]
> v2.3已打包windows版本
> 已保存配置
> ![image](https://user-images.githubusercontent.com/63721558/188278337-63f490a6-09df-40b7-80ef-4078893f01d1.png)
> 搜索引擎也选择fofa了，可为什么报错
> ![image](https://user-images.githubusercontent.com/63721558/188278358-f1be22cc-58f6-47e6-a108-5b1f76c965a0.png)

根据报错信息可能是代理出了问题，尝试关闭电脑的代理服务
