### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by 927986178** [xzajyjs/ThunderSearch#9]
mac inter 19 pro 黑屏了，什么原因呀？

**Comment by xzajyjs** [comment]
编译运行查看一下报错信息，并贴上来

**Comment by 927986178** [comment]
我的原因，不好意思，解决了，给大佬添麻烦了，工具无敌！

**Comment by 927986178** [comment]
fofa报错：
[!] Error: HTTPSConnectionPool(host='fofa.info', port=443): Max retries exceeded with url: /api/v1/search/all (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

**Comment by 927986178** [comment]
请问怎么解决一下

**Comment by xzajyjs** [comment]
fofa的限制，可能是查询次数过多、太频繁。尝试等待半小时并关闭代理重新查询

**Comment by 927986178** [comment]
已解决，确实！关闭了代理！抱拳！

**Comment by 927986178** [comment]
<img width="779" alt="图片" src="https://user-images.githubusercontent.com/64681877/196362395-ab0d84d7-9a2e-4ef0-bcd3-2abf692ac98e.png">

**Comment by 927986178** [comment]
黑屏无法解决，通过你发布的版本，又报上面的错误，关了代理也不行，我的环境python3.9 mac book pro 2019

**Comment by xzajyjs** [comment]
使用2.3版本
